mandatoryAccounts:
  - name: Management
    description: >-
      The management (primary) account. Do not change the name field for this
      mandatory account. Note, the account name key does not need to match the
      AWS account name.
    email: chazalf+alz-noct@amazon.com
    organizationalUnit: Root
  - name: LogArchive
    description: >-
      The log archive account. Do not change the name field for this mandatory
      account. Note, the account name key does not need to match the AWS account
      name.
    email: chazalf+alz-noct-logArchive@amazon.com
    organizationalUnit: Security
  - name: Audit
    description: >-
      The security audit account (also referred to as the audit account). Do not
      change the name field for this mandatory account. Note, the account name
      key does not need to match the AWS account name.
    email: chazalf+alz-noct-audit@amazon.com
    organizationalUnit: Security
workloadAccounts:
  - name: CICD
    description: The account hosting all the CI/CD tools
    email: chazalf+alz-noct-cicd@amazon.com
    organizationalUnit: SharedServices
  # - name: Dev
  #   description: The account hosting dev workloads
  #   email: chazalf+alz-noct-dev@amazon.com
  #   organizationalUnit: SDLC
  # - name: Prod
  #   description: The account hosting dev workloads
  #   email: chazalf+alz-noct-prod@amazon.com
  #   organizationalUnit: SDLC