customizations:
  cloudFormationStacks:
    - deploymentTargets:
        organizationalUnits:
          - SDLC
      description: Project A - Auto CDK bootstrap stack
      name: ProjectA-CDK-Bootstrap
      regions:
        - eu-west-1
      runOrder: 1
      template: bootstap-templates/cdk-bootstrap-template-v14.yml
      terminationProtection: false
      parameters:
        - name: TrustedAccounts
          value: '["257633838593"]'
        - name: Qualifier
          value: ProjectA
    - deploymentTargets:
        accounts:
          - CICD
      description: Project A - CICD - Auto CDK bootstrap stack
      name: ProjectA-CICD-CDK-Bootstrap
      regions:
        - eu-west-1
      runOrder: 1
      terminationProtection: false
      template: bootstap-templates/cdk-bootstrap-template-v14.yml
      parameters:
        - name: Qualifier
          value: ProjectA
