providers: []
policySets:
  - deploymentTargets:
      organizationalUnits:
        - Root
    policies:
      - name: MFA-Policy
        policy: iam-policies/MFA-policy.json
  - deploymentTargets:
      organizationalUnits:
        - Infrastructure
    policies:
      - name: DeveloperAccessIAMPolicy
        policy: iam-policies/DeveloperAccessIAMPolicy.json
      - name: DevOpsAccessIAMPolicy
        policy: iam-policies/DevOpsAccessIAMPolicy.json
roleSets: []
groupSets: []
userSets: []
identityCenter:
  name: identityCenter1
  identityCenterPermissionSets:
    - name: AdministratorAccess
      policies:
        awsManaged:
          - arn:aws:iam::aws:policy/AdministratorAccess
      sessionDuration: 60
  identityCenterGroups:
    - name: DevOps
      description: DevOps group
  identityCenterAssignments:
    - name: DevOps
      permissionSetName: AdministratorAccess
      principalName: DevOps
      principalType: GROUP
      deploymentTargets:
        organizationalUnits:
          - SharedServices
    - name: UserAssignmentTest
      permissionSetName: AdministratorAccess
      principalId: 'e2359414-a011-7044-f3b5-4831b2d06e22'
      principalType: USER
      deploymentTargets:
        organizationalUnits:
          - Security